### PR TITLE
make PortStack implement the netdever interface

### PR DESCRIPTION
**Pull request by scottfeldman**
In an effort to get drivers/examples/net example apps to run against cyw43439 + seqs/stack, implement netdever interface on PortStack.

Implement enough to get link UP and get a DHCP IP addr.  Socket() on function are not implemented, just stubbed out.

### CODE REVIEW

**Comment by scottfeldman** [comment]
Requires changes to tinygo-org/devices and soypat/cyw43439 repos:

https://github.com/tinygo-org/drivers/compare/dev...scottfeldman:cyw43439?expand=1
https://github.com/soypat/cyw43439/pull/32

**Comment by soypat** [comment]
Hey scott! At a glance it feels like this logic does not belong in `seqs` package but rather as part of the `tinygo/drivers` package that should use `seqs` to implement the netlink/netdev interfaces. Most logic I see here seeks to implement these interfaces, which is sort of glue code which could easily be in another package. I'm also on the fence with the code since I still feel like the tinygo/drivers netlink+netdev interfaces need some redesigning.

**Comment by scottfeldman** [comment]
Yes, we can break this into another package which uses seqs.

**Comment by scottfeldman** [comment]
This goes with these:

https://github.com/soypat/cyw43439/pull/32
https://github.com/tinygo-org/drivers/compare/dev...scottfeldman:drivers:cyw43439?expand=1

**Pull request closed without merging**
